### ISSUE TITLE
Buran not following redirect?

### ISSUE THREAD

**Issue by acidus99** [Corewala/Buran#38] opened 2023-03-18 14:40 UTC
I'm noticing something odd with 31 redirects.

Going to `gemini://gemi.dev/tests/` link works just fine:

Going to `gemini://gemi.dev/tests` (no trailing slash), the serve sends a `31` redirect to `gemini://gemi.dev/tests/`. Other clients follow it. Buran 1.12 just spins and spins the progress bar

Can you reproduce it? Its kind of driving me crazy

**Comment by mediocregopher** [comment] 2023-03-30 19:56
@acidus99 this is probably a duplicate of #33 , there just hasn't been a new Buran version released with the fix.

**Comment by Corewala** [comment] 2023-04-04 16:09
Again, so sorry I'm not doing more work on this, but yeah @mediocregopher is right this is the same bug. ([73afc7c](https://github.com/Corewala/Buran/commit/73afc7c684b9983f87aa19f954ef6ce1df99360f)) should fix it in the next release, which I hope to make once my courseload thins out later this april.

**Closed as completed by Corewala** 2023-04-04 16:09 UTC

**Comment by acidus99** [comment] 2023-04-04 17:25
No worries. thanks for making Buran! Its great
